import { signInWithPin } from '../api/authApi.js';
import { userStore } from '../state/userStore.js';

let currentPin = '';

function getDOMElements(){return{loginForm:document.querySelector('.login-form-container'),pinDots:document.querySelectorAll('.pin-dot'),errorMessage:document.getElementById('login-error-message'),numpad:document.getElementById('numpad')}}
function updatePinDisplay(){const{pinDots}=getDOMElements();pinDots.forEach((dot,index)=>{if(index<currentPin.length){dot.classList.add('active');if(index===currentPin.length-1){dot.classList.add('pulse');setTimeout(()=>dot.classList.remove('pulse'),200)}}else{dot.classList.remove('active','pulse')}})}
async function handleLogin(){const{loginForm,errorMessage}=getDOMElements();if(!loginForm||!errorMessage)return;loginForm.style.pointerEvents='none';errorMessage.textContent='';try{const userData=await signInWithPin(currentPin);if(userData){loginForm.classList.add('success');setTimeout(()=>{userStore.signIn(userData);window.location.reload()},700)}else{loginForm.classList.add('shake');errorMessage.textContent='รหัส PIN ไม่ถูกต้อง';setTimeout(()=>{loginForm.classList.remove('shake');currentPin='';updatePinDisplay();loginForm.style.pointerEvents='auto'},700)}}catch(error){errorMessage.textContent='เกิดข้อผิดพลาดในการเชื่อมต่อ';loginForm.style.pointerEvents='auto'}}
function handleNumpad(event){const key=event.target.dataset.key;if(!key)return;const{errorMessage}=getDOMElements();if(errorMessage.textContent){errorMessage.textContent=''}if(key==='clear'){currentPin=''}else if(key==='backspace'){currentPin=currentPin.slice(0,-1)}else if(currentPin.length<4){currentPin+=key}updatePinDisplay();if(currentPin.length===4){handleLogin()}}
export function LoginPage(){currentPin='';const view=`<div class="login-page-background" id="animated-bg"></div><div class="login-form-container"><h1 class="login-title">AUTHENTICATION</h1><p class="login-subtitle">กรุณายืนยันตัวตนด้วยรหัสพิน</p><div class="pin-display" id="pin-display"><div class="pin-dot"></div><div class="pin-dot"></div><div class="pin-dot"></div><div class="pin-dot"></div></div><p id="login-error-message" class="login-error"></p><div class="numpad" id="numpad"><button class="numpad__button" data-key="1">1</button><button class="numpad__button" data-key="2">2</button><button class="numpad__button" data-key="3">3</button><button class="numpad__button" data-key="4">4</button><button class="numpad__button" data-key="5">5</button><button class="numpad__button" data-key="6">6</button><button class="numpad__button" data-key="7">7</button><button class="numpad__button" data-key="8">8</button><button class="numpad__button" data-key="9">9</button><button class="numpad__button" data-key="clear">C</button><button class="numpad__button" data-key="0">0</button><button class="numpad__button" data-key="backspace">⌫</button></div></div>`;const postRender=()=>{setTimeout(()=>{const{numpad}=getDOMElements();numpad?.addEventListener('click',handleNumpad)},0)};return{view,postRender}}
